### ISSUE TITLE
Do a default message characters size customizable

### ISSUE THREAD

**Issue by initd** [loafoe/mattermost-client#109]
Mattermost-server v.5.0.0+ supports message size up to 16383 characters. Please see the change notes: https://docs.mattermost.com/administration/important-upgrade-notes.html

It will be better if variable **messageMaxRunes** (client.js) will be customizable via environment variables for example like this:

`
const messageMaxRunes = (process.env.MATTERMOST_MSG_CHUNK_SIZE || '16383');
`
It is a real production necessity
Thanks

**Comment by DanielRuf** [comment]
Hi, I would not really use environment variables for this.
Because makes it harder to use it as browser bundle.

**Comment by initd** [comment]
Ok, no problem. As you want. So, what options do we have to make this var customizable? You are already using env vars in this file below. 

Thanks

**Comment by DanielRuf** [comment]
The `env` part was some old solution. We will refactor this. We will add this as parameter to the constructor.

**Comment by initd** [comment]
Sounds good. Thanks

**Comment by DanielRuf** [comment]
Hi @initd,

we have a new fork at https://github.com/bitExpert/mattermost-client-node which has many improvements and should already include this.

I think we can implement it there.

**Comment by initd** [comment]
Hi @DanielRuf,
glad to hear that, thanks! I think we can close this issue)
