### ISSUE TITLE
feature request: gitlab login

### ISSUE THREAD

**Issue by tquid** [loafoe/mattermost-client#18]
It appears we can't log in using gitlab, only straight username + password.

If you know any client that can get into Mattermost using a gitlab authentication token(?), I'd be happy to try to set it up, but I'm a bit of a noob and this is the first Mattermost client I've dealt with, and my searches haven't turned up anything.

**Comment by loafoe** [comment]
@tquid if you use Gitlab SSO you unfortunately need to manually create a username/password combination using the mattermost command line tool. There is currently no way to use Gitlab SSO to log in the Hubot client. Ideally Mattermost should get support for actual Bot users. Now we are just pretending to be real users.
