### ISSUE TITLE
mattermost client not proxy aware.

### ISSUE THREAD

**Issue by ThetaGamma** [loafoe/mattermost-client#22]
Unfortunately the mattermost client is not proxy aware. This leads to the effect, that everything within mattermost client, which is based on HTTPS request (so i.e. everything within function "_apiCall") will be perfectly routed through a proxy, if the corresponding environment variables are set.

But the calls in "connect: ->" are based on WebSocket, which are not proxy-aware. So if you wireshark the connection, you see all request through the proxy and the Websocket calls are tried directly.

**Comment by vrenjith** [comment]
Any hints on how to solve this?

**Comment by loafoe** [comment]
@vrenjith unfortunately no. I guess we need to first replace WebSocket with something that is proxy aware, but I'm not aware of another JS/Coffee implementation for websocket support.

**Comment by vrenjith** [comment]
Thanks Andy. I am experimenting with a transparent proxy which supports
websockets to make this work. Will keep this thread updated.

**Comment by loafoe** [comment]
@vrenjith Ok great!

**Comment by louis-gounot** [comment]
Hello,

It is possible to use HTTPS proxy through WebSocket.
You have to include https-proxy-agent in your requirements.

Then add something like this to client.coffe (requires a few if to check if proxy var is set) : 
```
url = require('url');
HttpsProxyAgent = require('https-proxy-agent');
proxy = process.env.https_proxy
agent = new HttpsProxyAgent(url.parse(proxy));
```
And add
`agent: agent`
to your WebSocket options.

Can't make a PR right now, will try to find some time later.

Regards

**Comment by loafoe** [comment]
@stonyz implemented this, thx! /cc @ThetaGamma @vrenjith @louis-gounot please test!
