### ISSUE TITLE
Mattermost 3.4 Support

### ISSUE THREAD

**Issue by ABitMoreDepth** [loafoe/mattermost-client#23]
Does this system support Mattermost 3.4 yet?  I've had a few issues successfully connecting a hubot instance to Mattermost, from the debugging I've managed to do so far, it looks like there is an issue when trying to login, which is handled in this repo?

What can I provide in order to help figure this out?

**Comment by cadecairos** [comment]
I've been struggling with this too - It looks like a bug was introduced in #21 that causes the string "undefined" to become appended to the uri of the login request.

@loafoe I can provide a fix in the next couple days (I'm a bit busy right now).

And while I've got your attention, I'm working on implementing the API call to Mattermost for updating a channel header. We're hoping to use it to update specific channels with information about the current on-call engineer. I'll file PRs when I get it working.

**Comment by cadecairos** [comment]
@loafoe Thanks for merging my PRs!

Can you publish a new version of the client to npm? Then we can bump the package version in the hubot adapter and publish a new version there as well.

**Comment by loafoe** [comment]
@cadecairos currently heading for airport.. depending on GoGo inflight service it will be out later today, if not tomorrow.

**Comment by cadecairos** [comment]
This is great news, thanks!

**Comment by ABitMoreDepth** [comment]
Thanks @loafoe & @cadecairos!

I'm hitting a different issue where the bot logs in successfully but pauses after:
```
INFO Logging in...
INFO Websocket URL: ws://mattermost.example.internal:443/api/v3/users/websocket
INFO Logged in as user "hubot" but not connected yet.
INFO Connecting...
INFO Error: Error: read ECONNRESET
INFO Reconnecting in 1000ms
INFO Attempting reconnect
INFO Logging in...
INFO Websocket URL: ws://mattermost.example.internal:443/api/v3/users/websocket
INFO Logged in as user "hubot" but not connected yet.
```

And doesn't seem to get any further.  I don't know if this is related to this issue or not, if not I'm happy to close this.

Thanks again for both your help!

**Comment by loafoe** [comment]
@ABitMoreDepth is mattermost.example.internal:443 a **ws** really (non secure) endpoint? There might be a mismatch in protocol type. It could be that you need to use wss:// there

**Comment by ABitMoreDepth** [comment]
Intriguingly it appears so, 

I'm using docker to run both mattermost and the hubot platform, the mattermost docker info is [here](https://github.com/mattermost/mattermost-docker),

I followed their instructions to get mattermost up and running, specifying not to use SSL as currently only deployed to our internal network, so no easy way to authenticate etc...

No-where in that docker-compose stuff does it look like they fidget with `ws` or `wss`, perhaps that is where my issue is...

Mattermost itself seems to be running pretty well, though I do notice socket disconnects from time to time.  Perhaps I will need to use a different mattermost docker setup.

**Comment by loafoe** [comment]
@ABitMoreDepth there are a lot of reports with issues on the Docker setup. I have not tried it myself, will see if I can find some time this month. Mattermost 3.5.0 is about to be released and the library has been updated to support it. Unfortunately it's not feasible to keep backwards compatibility so we only support the current version of MM.

**Comment by ABitMoreDepth** [comment]
Thats not a problem, I'll to migrate to the new version when it lands and let you know if I still find an issue.
