### ISSUE TITLE
Add support for file uploads

### ISSUE THREAD

**Issue by ssc2015** [loafoe/mattermost-client#28]
@loafoe,

Is there any work already in progress to support file uploads?

**Comment by loafoe** [comment]
@ssc2015 looking into it yes, I'm using the Go client for this though in my own projects at this time.

**Comment by stonyz** [comment]
Added a api for it.  
`
channelId='sxe84mdeibd8xyu5i1fx7eyskw'
file = '/Users/stonyz/Desktop/aaa.png'
client.on 'channelsLoaded', () -> 
    client.uploadFile channelId, file , (resp) ->
        console.log JSON.stringify(resp)
        file_id = resp.file_infos[0].id;
        client.customMessage {message:'Test by Stony',file_ids:[file_id]}, channelId
`
