### ISSUE TITLE
Add emit event for 'channelsLoaded'

### ISSUE THREAD

**Issue by crymis** [loafoe/mattermost-client#29]
### In client.coffee:
Similar to 'ProfilesLoaded' in line 91.
`@emit 'profilesLoaded', { profiles: @users }`

the _onChannels method should emit a 'channelsLoaded' event to be able to initially contact all users on startup.

=> Should be 
`@emit 'channelsLoaded', { channels: @channels }`
below line 98

_"I needed this function for an internal survey, where a chatbot sent the initial message!"_

**Comment by crymis** [comment]
Can you publish this change for npm? :)

**Comment by loafoe** [comment]
@crymis available now!
