### ISSUE TITLE
Webpack workaround

### ISSUE THREAD

**Issue by VincentSC** [loafoe/mattermost-client#294]
I cannot use `"mattermost-client": "github:loafoe/mattermost-client"` as a dependency, due to webpack.

Furthermore, the `require`-functions give problems, probably due to a different working directory. Also when there are problems, it always shows an error on line 1 and it's not easy to read.

The work-around is to manually copy the two other files into client.js and rename to dist/mattermost-client.js

Would it be possible to have a pre-built "dist" with code that is not packed to one line, that is up-to-date with the code? It is now in `.gitignore`. This makes it possible to use the github-dependency more easily. Also, could documentation or a bash-script be added, (how) to build this repo with webpack?

**Comment by Marthym** [comment]
Hi,

We will push a build version 6.4.2 (or 6.5.0) for npm soon. We didn't have time this week but we will do it as soon as possible. 

For your question about documentation, we will improve it but in the meantime  you can build with 

```js
yarn install
yarn build:dev  # for a non oneline build
yarn build:prod # for optimized build
```

**Comment by VincentSC** [comment]
Thanks!

Here's a start of the documentation. Testing is just a start and full of assumptions. But I thought: easier to comment and fix documentation, than to start from scratch. :)

# Development

This project does not support all the existing API-calls yet. It is appreciated if you implement the missing API-calls that you need in this plugin, instead of using the `raw API` call in your own code. This way more people are helped in the end. It often does not take much time to implement a new call, as the base is there for both the calls and the tests.

If you choose to do development on this code or use the module as a dependency in your own module, you need to create a distribution-pack for development. Best is to fork the repo, and remove`dist` from `.gitignore`, so you can use the live version more easily. Just make sure you don't add `dist` to the PR when upstreaming.

This project uses `yarn` for building, which can be installed via: 
> npm install --global yarn

Then you need to install yarn in the repo by running this in the root of the project:
> yarn install

You can then choose to build the dev-version with:
> yarn build:dev 

In case you want to build the packed 1-line version, you need to run:
> yarn build:prod

This will create the file `./dist/mattermost-client.js`. Every time you have made changes to the mattermost-client, you need to rerun that last command.

To start the implementation of the call, just start an issue, tell your intentions and assign to yourself. Thanks in advance of making this project better!

# Testing

Testing is done using `jest`, which can be installed via 
> yarn add --dev jest

Best to read this document, to understand how jest works. https://jestjs.io/docs/getting-started

The tests are all in `tests/client.test.js`. They all have a generic build up. It needs a dummy mattermost-installation available under `test.foo.bar` - easiest is to use Docker for that. *Some words on how to set up this local Docker easily*

**Comment by loafoe** [comment]
`v6.5.0` is available now
