### ISSUE TITLE
Selection of text can not be copied into the clipboard - only whole messages

### ISSUE THREAD

**Issue by SockenSalat** [loafoe/mattermost-client#357]
Mattermost-client 5.2.1 on Linux

When selecting text from a message and choosing `copy` from the context-menu the whole message is put into the clipboard instead of the selection.
This is very annoying, since one is required to open a text editor, paste the whole stuff and reselect the parts of interest.

**Comment by loafoe** [comment]
hi @SockenSalat , this is probably an issue to raise on the [mattermost-webapp](https://github.com/mattermost/mattermost-webapp), this project provides an API client without any UI components

**Comment by SockenSalat** [comment]
@loafoe thnx, I'll move the issue.

sorry for the confusion :+1:
