### ISSUE TITLE
Wrong message order if your hubot machine have time difference with mattermost server. 

### ISSUE THREAD

**Issue by iUkka** [loafoe/mattermost-client#39]
If your hubot machine have different time with mattermost server you may recieve wrong message order between you and hubot.

![image](https://user-images.githubusercontent.com/5823637/28742994-2378985e-7447-11e7-9662-c9a88b8873b6.png)

Resolve is simple:
on client.coffee  

    postMessage: (msg, channelID) ->
        postData =
            message: msg
            filenames: []
            create_at: Date.now()    <-------- change to create_at: 0
            user_id: @self.id
            channel_id: channelID

**Comment by loafoe** [comment]
@iUkka should be fixed
