### ISSUE TITLE
Can you give some suggestion to develop coffescript?

### ISSUE THREAD

**Issue by stonyz** [loafoe/mattermost-client#43]
@loafoe Even though I have pushed some code to it, but my development process is really slow! I can't debug in IDE, just add some log to check bug. can you give me some help on it? What I need is to debug code in IDE step by step.  BTW, I'm using VSCode. 

Sorry I know it's not a good place to ask question here, but I really want to your help. thanks a lot in advance.

**Comment by stonyz** [comment]
Thanks for your reply. I got a solution, but not sure if it's the best. 
I use VS Code + grunt.  add the following to package.json,

```
  "devDependencies": {
    "grunt": "^1.0.1",
    "grunt-contrib-coffee": "^1.0.0",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-jshint": "^1.1.0",
    "grunt-contrib-watch": "^1.0.0"
  }
```

and the Gruntfile.js is,

module.exports = function(grunt) {
    
      // Project configuration.
      grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        uglify: {
          options: {
            banner: '/*! <%= pkg.name %> <%= grunt.template.today("yyyy-mm-dd") %> */\n'
          },
          build: {
            src: 'src/<%= pkg.name %>.js',
            dest: 'build/<%= pkg.name %>.min.js'
          }
        },
        coffee:{
            compileWithMaps: {
                options: {
                    sourceMap: true
                  },
                  files: {
                    'coffeejs/client.js': ['src/client.coffee'],
                    'coffeejs/message.js': ['src/message.coffee'],
                    'coffeejs/user.js': ['src/user.coffee'],
                    'coffeejs/client_test.js': 'src/client_test.coffee',
                  }
              }
        },
        copy:{
            main:{
                files:[
                    {expand: true, cwd: 'src', src: ['**/*.coffee'], dest: 'coffeejs/'},
                ]
            }
        },
        watch: {
            scripts: {
              files: ['src/**/*.coffee'],
              tasks: ['coffee:compileWithMaps','copy'],
              options: {
                spawn: false,
              },
            },
          }
      });
    
      grunt.loadNpmTasks('grunt-contrib-coffee');
      grunt.loadNpmTasks('grunt-contrib-copy');
      grunt.loadNpmTasks('grunt-contrib-watch');
    };

**Comment by loafoe** [comment]
@stonyz I'll try your setup, thx!
