### ISSUE TITLE
Need some assistance

### ISSUE THREAD

**Issue by yocode** [loafoe/mattermost-client#48]
The Docker Build and Run went fine and I was put into the hubot cli when I ran the container.

[jonathanKlein@mattermost-demo-docker-instance hubot-matteruser]$ sudo docker run -it -p 8080:8080 --env MATTERMOST_HOST=chat.pwcdatasieve.com --env MATTERMOST_GROUP=innovation --env MATTERMOST_USER=jarvis@pwc --env MATTERMOST_PASSWORD=BotsAreCool --env MATTERMOST_SELFSIGNED_CERT=true --env MATTERMOST_HUBOT_USERNAME=jarvis --env --name hubot-matteruser hubot-matteruser
npm info it worked if it ends with ok
npm info using npm@2.15.11
npm info using node@v4.8.4
npm info preinstall jarvis@0.0.0
npm info package.json hubot-scripts@2.17.2 No license field.
npm info build /usr/src/hubot-matteruser
npm info linkStuff jarvis@0.0.0
npm info install jarvis@0.0.0
npm info postinstall jarvis@0.0.0
npm info prepublish jarvis@0.0.0
npm info ok
jarvis> [Thu Oct 19 2017 14:23:08 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379

jarvis>
jarvis> jarvis help
jarvis> jarvis adapter - Reply with the adapter
ETC…

do I also need the mattermost-client installed?
github.com

loafoe/mattermost-client

mattermost-client - Mattermost client using websockets
I having trouble following the steps in the installation instructions.

Thanks!

**Comment by loafoe** [comment]
@yocode mattermost-client is a dependency of hubot-matteruser so it will be pulled in as part of the adapter itself, no need to install it separately.

The docker image should connect to your MatterMost server though. 

Looks like you have an extra __`--env`__ param near the end of your docker run line. Can you try it again after removing it?

**Comment by yocode** [comment]
Hey Andy,

Thanks for your quick reply. The issue was with my nginx reverse proxy. I didn't have "proxy_set_header" configured to allow http to upgrade to websockets.

Everything is working as expected. except....

jarvis
9:42 AM
http://i.imgur.com/CzFTOkI.png

9:42 AM
Google Image Search API is no longer available. Please setup up Custom Search Engine API.

It looks like hubot-matteruser is using a depreciated api. or did I misconfigure something?

Thanks Again!

**Comment by loafoe** [comment]
@yocode hi , glad to hear it's resolved! 

Regarding Google Image Search, looks like one of the plugins you are using could be using a deprecated API yes, the adapter itself does not talk to Google API. Which plugins did you install?

**Comment by at4446** [comment]
@loafoe do I have install mattermost first and theninstall mattermost-client?

**Comment by loafoe** [comment]
@at4446 you need a server running somewhere yes
