### ISSUE TITLE
Allow adding headers and add X-Requested-With

### ISSUE THREAD

**Issue by HagenMorano** [loafoe/mattermost-client#57]
https://github.com/loafoe/mattermost-client/blob/9822ee5293140d797debf286feb6905ee8732780/src/client.js#L611-L627

To be able to receive the `set-cookie` (`MMAUTHTOKEN`, `MMUSERID`, `MMCSRF`) headers, add `'X-Requested-With': 'XMLHttpRequest'` to headers in options in `_apiCall`.

Suggestion: Add `headers` option to `options` like 
```
{
   wssPort: 443, 
   httpPort: 80, 
   headers: {'X-Requested-With': 'XMLHttpRequest', 'date': '123', [...]} 
}
``` 
and merge with existing headers like `Object.assign({}, existingHeaders, this.options.headers)`

**Comment by DanielRuf** [comment]
@loafoe bump.

We would also provide many bigger PRs.

**Comment by loafoe** [comment]
@HagenMorano @DanielRuf can you provide a PR for this? Thx!

**Comment by HagenMorano** [comment]
Here we go:
https://github.com/loafoe/mattermost-client/pull/85  

I'll create a different ticket for the headers feature.
