### ISSUE TITLE
Update to newest api? (v3)

### ISSUE THREAD

**Issue by Q-efx** [loafoe/mattermost-client#6]
As stated in release note:

> Web Service API is upgraded to Version 3 and previous Version 1 API is no longer supported. Golang driver, Javascript driver, incoming and outgoing webhooks and Slash commands continue to function as in previous release

Will we see an update?

**Comment by loafoe** [comment]
@Q-efx the `v3` branch has support. I'll create an official release shortly

**Comment by loafoe** [comment]
Version `3.0.0` was releases which support Mattermost `3.0+` (only)
