### ISSUE TITLE
Logging in with Gitab SSO

### ISSUE THREAD

**Issue by alexiri** [loafoe/mattermost-client#8]
Is there a way to log in when the server is configured with Gitlab SSO exclusively?

**Comment by loafoe** [comment]
There is: you need to create a non-SSO user manually using the mattermost platform binary:

`platform -create_user -team_name="name" -email="user@example.com" -password="mypassword"`

You can then proceed to use these credentials for logging your bot into Mattermost.

**Comment by loafoe** [comment]
Also make sure **Allow Sign In With Email** is enabled if you are using Mattermost 3.0
