### ISSUE TITLE
listening to post reactions

### ISSUE THREAD

**Issue by fculpo** [loafoe/mattermost-client#90]
We have a fun need of sending a kick command if a message gets a fixed number of a defined reaction (let's say hammer)

I don't see any get_reaction or related  method, is there a way to do this already ?

**Comment by DanielRuf** [comment]
Hi @fculpo,

do you mean the `react` method?

https://github.com/loafoe/mattermost-client/blob/master/src/client.js#L501

**Comment by DanielRuf** [comment]
You should be able to keep track of this in the memory or some state on the side where this code runs, probably on NodeJS side.
